from exceptions import FolderInS3UriError

def run():
    print("Do some stuff with the exception: ", FolderInS3UriError)


if __name__ == "__main__":
    run()
